# Generated by Django 2.0.6 on 2019-06-03 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=11, verbose_name='用户名')),
                ('_password', models.CharField(max_length=128, verbose_name='密码')),
                ('mg_key', models.CharField(max_length=12, verbose_name='数据键')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
