# Generated by Django 2.0.6 on 2019-06-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=11, unique=True, verbose_name='用户名'),
        ),
    ]
